# Frontend/Dockerfile
FROM node:18-alpine

WORKDIR /app

# Install Vue CLI globally
RUN npm install -g @vue/cli

# Copy package.json and yarn.lock to install dependencies
COPY package.json yarn.lock /app/

# Install project dependencies
RUN yarn install

# Copy the rest of the project files into the container
COPY . /app/

# Expose the port
EXPOSE 8081

# Command to run the development server
CMD ["yarn", "serve"]
